version: '3'

services:
    mysql:
        image: mysql
        container_name: federation-mysql
        volumes:
            - federation-mysql:/var/lib/mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: password

volumes:
    federation-mysql:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/home/louisaldorio/federation-mysql'