// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewUser struct {
	Name string `json:"name"`
}

type Post struct {
	ID     int   `json:"id"`
	UserID int   `json:"user_id"`
	User   *User `json:"user"`
}

func (Post) IsEntity() {}

type User struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

func (User) IsEntity() {}
